# Generated by Django 5.2.4 on 2025-07-22 12:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0002_reservationstatusupdate'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='food_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='food_items', to='restaurants.category'),
        ),
    ]
