# Generated by Django 5.1.7 on 2025-08-02 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0003_menuitem_food_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='duration_hours',
            field=models.IntegerField(default=1, help_text='Duration in hours (minimum 1 hour)'),
        ),
        migrations.AddField(
            model_name='table',
            name='floor',
            field=models.CharField(choices=[('ground', 'Ground Floor'), ('first', 'First Floor'), ('second', 'Second Floor'), ('third', 'Third Floor'), ('fourth', 'Fourth Floor'), ('rooftop', 'Rooftop')], default='ground', max_length=20),
        ),
        migrations.AlterUniqueTogether(
            name='table',
            unique_together={('restaurant', 'table_number', 'floor')},
        ),
    ]
