# Generated by Django 5.2.4 on 2025-08-20 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0004_reservation_duration_hours_table_floor_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='table',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='duration_hours',
            field=models.IntegerField(default=1, help_text='Duration of reservation in hours'),
        ),
        migrations.RemoveField(
            model_name='table',
            name='floor',
        ),
    ]
