# Generated by Django 5.1.7 on 2025-08-22 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0005_alter_table_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='duration_hours',
            field=models.IntegerField(default=1, help_text='Duration of reservation in hours'),
        ),
    ]
