# Generated by Django 5.2.4 on 2025-07-22 12:19

from django.db import migrations

def update_staff_flag(apps, schema_editor):
    User = apps.get_model('accounts', 'User')
    # Update all staff members to have is_staff=True
    User.objects.filter(is_staff_member=True).update(is_staff=True)

class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_staffprofile_is_on_shift_staffshift'),
    ]

    operations = [
        migrations.RunPython(update_staff_flag),
    ]
