# Generated by Django 5.2.4 on 2025-07-23 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_update_staff_flag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordreset',
            name='code',
            field=models.CharField(max_length=4),
        ),
        migrations.AlterField(
            model_name='phoneverification',
            name='code',
            field=models.CharField(max_length=4),
        ),
    ]
