# Generated by Django 5.2.4 on 2025-07-23 11:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_passwordreset_code_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TokenVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.IntegerField(default=0)),
                ('last_logout', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='token_version', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
