# Generated by Django 5.2.4 on 2025-08-25 08:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0001_initial'),
        ('restaurants', '0006_auto_20250822_1903'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='recommendationlog',
            name='context',
            field=models.CharField(choices=[('menu', 'menu'), ('upsell', 'upsell'), ('semantic', 'semantic'), ('basic', 'basic'), ('chat', 'chat'), ('table_selection', 'table_selection')], max_length=20),
        ),
        migrations.CreateModel(
            name='TableSelectionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selection_method', models.CharField(choices=[('ai', 'AI Selection'), ('random', 'Random Fallback'), ('error_fallback', 'Error Fallback')], max_length=20)),
                ('available_tables_count', models.IntegerField()),
                ('available_tables_data', models.JSONField()),
                ('ai_reasoning', models.TextField(blank=True, null=True)),
                ('ai_confidence', models.FloatField(default=0.0)),
                ('ai_factors_considered', models.JSONField(default=list)),
                ('ai_alternative_table_id', models.IntegerField(blank=True, null=True)),
                ('party_size', models.IntegerField()),
                ('reservation_date', models.DateField()),
                ('reservation_time', models.TimeField()),
                ('duration_hours', models.IntegerField()),
                ('special_occasion', models.CharField(blank=True, max_length=100, null=True)),
                ('user_preferences', models.JSONField(default=dict)),
                ('ai_response_time_ms', models.IntegerField(blank=True, null=True)),
                ('ai_success', models.BooleanField(default=True)),
                ('ai_error_message', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reservation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ai_selection_log', to='restaurants.reservation')),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restaurants.restaurant')),
                ('selected_table', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restaurants.table')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
