# Generated by Django 5.2.4 on 2025-07-21 10:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='orderstatusupdate',
            name='is_notified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='orderstatusupdate',
            name='notification_message',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='orderstatusupdate',
            name='updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_status_updates', to=settings.AUTH_USER_MODEL),
        ),
    ]
