# Generated by Django 5.1.7 on 2025-08-23 16:08

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0002_orderstatusupdate_is_notified_and_more'),
        ('restaurants', '0006_auto_20250822_1903'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('notification_type', models.CharField(choices=[('order_placed', 'Order Placed'), ('order_confirmed', 'Order Confirmed'), ('order_preparing', 'Order Preparing'), ('order_ready', 'Order Ready'), ('order_delivered', 'Order Delivered'), ('order_cancelled', 'Order Cancelled'), ('reservation_confirmed', 'Reservation Confirmed'), ('reservation_reminder', 'Reservation Reminder'), ('reservation_cancelled', 'Reservation Cancelled'), ('payment_success', 'Payment Success'), ('payment_failed', 'Payment Failed'), ('promotion', 'Promotion'), ('general', 'General')], max_length=50)),
                ('title_template', models.CharField(max_length=255)),
                ('body_template', models.TextField()),
                ('data_template', models.JSONField(blank=True, default=dict)),
                ('image_url', models.URLField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'notifications_template',
                'unique_together': {('notification_type', 'name')},
            },
        ),
        migrations.CreateModel(
            name='FCMToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.TextField(unique=True)),
                ('device_type', models.CharField(choices=[('android', 'Android'), ('ios', 'iOS'), ('web', 'Web')], default='android', max_length=20)),
                ('device_id', models.CharField(blank=True, max_length=255, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_used', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fcm_tokens', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'notifications_fcm_token',
                'indexes': [models.Index(fields=['user', 'is_active'], name='notificatio_user_id_fcd939_idx'), models.Index(fields=['token'], name='notificatio_token_76ab3e_idx')],
            },
        ),
        migrations.CreateModel(
            name='NotificationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(max_length=50)),
                ('title', models.CharField(max_length=255)),
                ('body', models.TextField()),
                ('data', models.JSONField(blank=True, default=dict)),
                ('fcm_token', models.TextField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('failed', 'Failed'), ('delivered', 'Delivered')], default='pending', max_length=20)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('firebase_message_id', models.CharField(blank=True, max_length=255, null=True)),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='orders.order')),
                ('reservation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='restaurants.reservation')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'notifications_log',
                'indexes': [models.Index(fields=['user', 'sent_at'], name='notificatio_user_id_c510b0_idx'), models.Index(fields=['notification_type', 'status'], name='notificatio_notific_2584f4_idx'), models.Index(fields=['sent_at'], name='notificatio_sent_at_f4f6e0_idx')],
            },
        ),
        migrations.CreateModel(
            name='TopicSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(choices=[('order_updates', 'Order Updates'), ('restaurant_news', 'Restaurant News'), ('promotions', 'Promotions'), ('system_alerts', 'System Alerts')], max_length=50)),
                ('is_subscribed', models.BooleanField(default=True)),
                ('subscribed_at', models.DateTimeField(auto_now_add=True)),
                ('unsubscribed_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topic_subscriptions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'notifications_topic_subscription',
                'unique_together': {('user', 'topic')},
            },
        ),
    ]
